export const DAILY_CHALLENGES = Object.freeze([
  {
    id: "daily-2026-09-18",
    date: "2026-09-18",
    answer: "stare",
    letters: "ertas",
    clue: "Look fixedly at something for a long moment.",
    difficulty: "easy",
    maxAttempts: 6,
    acceptedAnagrams: ["aster", "rates", "resat", "stare", "tares", "taser", "tears"],
  },
  {
    id: "daily-2026-09-19",
    date: "2026-09-19",
    answer: "scrape",
    letters: "peracs",
    clue: "Rub a surface with something rough or sharp.",
    difficulty: "medium",
    maxAttempts: 6,
    acceptedAnagrams: ["capers", "crapes", "pacers", "parsec", "recaps", "scrape", "spacer"],
  },
  {
    id: "daily-2026-09-20",
    date: "2026-09-20",
    answer: "reacts",
    letters: "sectar",
    clue: "Responds to an event, action, or change.",
    difficulty: "medium",
    maxAttempts: 6,
    acceptedAnagrams: ["carets", "caster", "caters", "crates", "reacts", "recast", "traces"],
  },
  {
    id: "daily-2026-09-21",
    date: "2026-09-21",
    answer: "staple",
    letters: "tlepas",
    clue: "A small bent fastener used to hold papers together.",
    difficulty: "easy",
    maxAttempts: 6,
    acceptedAnagrams: ["palest", "pastel", "petals", "plates", "pleats", "septal", "staple"],
  },
  {
    id: "daily-2026-09-22",
    date: "2026-09-22",
    answer: "spear",
    letters: "aersp",
    clue: "A long weapon with a pointed tip.",
    difficulty: "easy",
    maxAttempts: 6,
    acceptedAnagrams: ["pares", "parse", "pears", "rapes", "reaps", "spare", "spear"],
  },
  {
    id: "daily-2026-09-23",
    date: "2026-09-23",
    answer: "beast",
    letters: "staeb",
    clue: "A large or dangerous animal, especially in a story.",
    difficulty: "medium",
    maxAttempts: 5,
    acceptedAnagrams: ["abets", "baste", "bates", "beast", "beats", "betas"],
  },
  {
    id: "daily-2026-09-24",
    date: "2026-09-24",
    answer: "steal",
    letters: "alest",
    clue: "Take something without permission or right.",
    difficulty: "hard",
    maxAttempts: 5,
    acceptedAnagrams: ["least", "slate", "stale", "steal", "tales", "teals"],
  },
]);
