// ------------------------------------------------------------
// WordCabin Dictionary Generation Module
// ------------------------------------------------------------

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

async function loadExistingCommonWords(productionDictionaryPath) {
    if (!fs.existsSync(productionDictionaryPath)) {
        return new Set();
    }

    const fileUrl = pathToFileURL(productionDictionaryPath).href;
    const existingModule = await import(`${fileUrl}?cacheBust=${Date.now()}`);

    if (!Array.isArray(existingModule.WORDS)) {
        return new Set();
    }

    return new Set(
        existingModule.WORDS
            .filter((entry) => entry && entry.common === true && typeof entry.w === "string")
            .map((entry) => entry.w)
    );
}

function buildDictionaryEntries(words, commonWords) {
    return words.map((word) => ({
        w: word,
        common: commonWords.has(word),
    }));
}

function buildOutputFileContent(entries) {
    return [
        "// WordCabin production dictionary.",
        "// This file is generated by tools/dictionary/build-dictionary.js.",
        "// Do not edit manually. Update dictionary sources and rerun the builder.",
        `export const WORDS = ${JSON.stringify(entries)};`,
        "",
    ].join("\n");
}

export async function generateDictionary(normalizedResult, qaResult, config) {
    console.log("");
    console.log("==============================");
    console.log("Generation Stage");
    console.log("==============================");

    if (!qaResult || qaResult.passed !== true) {
        throw new Error("Generation failed: QA must pass before dictionary generation.");
    }

    if (!normalizedResult || !Array.isArray(normalizedResult.words)) {
        throw new Error("Generation failed: normalized result is missing words array.");
    }

    if (!config || !config.productionDictionary) {
        throw new Error("Generation failed: config.productionDictionary is missing.");
    }

    const outputPath = config.productionDictionary;
    const outputDirectory = path.dirname(outputPath);

    fs.mkdirSync(outputDirectory, { recursive: true });

    const commonWords = await loadExistingCommonWords(outputPath);
    const entries = buildDictionaryEntries(normalizedResult.words, commonWords);
    const fileContent = buildOutputFileContent(entries);

    fs.writeFileSync(outputPath, fileContent, "utf8");

    const generatedStats = fs.statSync(outputPath);
    const commonWordCount = entries.filter((entry) => entry.common === true).length;

    const generationReport = {
        outputPath,
        outputFileName: path.basename(outputPath),
        generatedWordCount: entries.length,
        commonWordCount,
        nonCommonWordCount: entries.length - commonWordCount,
        sizeBytes: generatedStats.size,
        sampleEntries: entries.slice(0, 20),
    };

    console.log("Generation report:");
    console.log("Generation completed.");

    return generationReport;
}